### ISSUE TITLE
Error in install.packages : object 'DSSAT' not found

### ISSUE THREAD

**Issue by hy9jp1** [palderman/DSSAT#28]
I am trying to install the DSSAT package in order to use the mutate_cond function, but keep getting the following error:

> install.packages(DSSAT)
Error in install.packages : object 'DSSAT' not found

DSSAT is also not coming up via the search function under packages or help.

Any ideas?

**Comment by palderman** [comment]
Try `install.packages("DSSAT")` with quotes
