### ISSUE TITLE
write_sol does not save the changes

### ISSUE THREAD

**Issue by jprakash23** [palderman/DSSAT#29]
I tried to modify some soil parameters but write_sol does not save it, even after append = F, force_std_fmt = F
## Step 1: read soil file
sol <- read_sol('SOIL.SOL')

## Step 2: Increase SBDM values
sol$SBDM[[1]] <-  sol$SBDM[[1]]  + 1

## Step 3: Save the modified sol
write_sol(sol, new_filename)

**Comment by palderman** [comment]
Hi @jprakash23, thanks for reporting this. I think I have been able to diagnose the problem, but would you be able to post a soil file with a single soil profile you are working with?

I would like to test against your file to be sure that my solution works with your data.

**Comment by palderman** [comment]
I think this issue is related to #23.

**Comment by jprakash23** [comment]
@palderman here is the soil file. Please have a look and if your solution works, please inform me. 
[SOIL.txt](https://github.com/palderman/DSSAT/files/6886571/SOIL.txt)

**Comment by palderman** [comment]
Ok. It looks like the changes I have in the develop branch should resolve this issue.

I plan to bundle these changes with a few more and submit a new version to CRAN later this week or early next week.

If you need it sooner you can install from the develop branch:

```
devtools::install_github("palderman/DSSAT", ref = "develop")
```

**Comment by jprakash23** [comment]
Great help!!! It works perfectly. Thank a lot @palderman
