### ISSUE TITLE
speed up read_sol function 

### ISSUE THREAD

**Issue by AnnaBlanke** [palderman/DSSAT#41]
Hi! 
I am trying to read in soil data produced by https://www.sciencedirect.com/science/article/pii/S1364815218313033. They come in a 10km^2 resolution for different countries. Reading these soil data with the read_sol function takes very long. Any idea how I could speed that up? The dataset I am trying to read in has  ~100,000 lines. 
Thank you!

**Comment by palderman** [comment]
Hi @AnnaHampf,

That is an excellent question. My motivating use case with this function was for manipulating a single or small set of profiles, so speed wasn't necessarily a primary consideration. The way the code is currently each profile is parsed separately. If I had to guess, I would think that the multiple dispatching of the function for parsing each profile is the main slow down. If so, we might develop a strategy whereby we process the data for multiple profiles in a single step and then split those data into their respective profiles in a subsequent step.

Let me do some profiling and get back to you.

**Comment by palderman** [comment]
The profiling revealed more or less what I expected. I think the strategy I outlined is probably our best bet.

Before I start fiddling with code, I need to implement some unit testing to make sure that I don't break anything in the process. I should be able to get the tests implemented today, but I won't get to the revision of the function itself until early next week.

**Comment by AnnaHampf** [comment]
Great! Thanks a lot for providing this great package and improving it. I was able to read in the soil data using read_sol function on our cluster (took some hours, but it worked :)) and do the required data manipulation, so no need to rush from my side :)

**Comment by palderman** [comment]
Hi @AnnaBlanke,

It took longer than anticipated (as usual, I suppose), but I think I managed to speed things up quite a bit. My tests indicate a more than 30x speedup with this strategy. Would you be able to install the current develop branch and try it out on a subset of the dataset you are working with to see if you see similar speedups?

You can install the current develop branch with:

```
devtools::install_github("palderman/DSSAT", ref = "develop")
```

I have run all these changes through testing and everything seems stable, but do let me know if you notice anything amiss.

**Comment by AnnaBlanke** [comment]
Hi @palderman! 
I just tested the read_sol function from the develop branch and I can confirm the 30x speedup! :) Thanks a lot!
