### ISSUE TITLE
Problem with write_eco ?

### ISSUE THREAD

**Issue by sbuis** [palderman/DSSAT#42]
Hi Phillip,

run_dssat() give the following error after an eco file has been written using the write_eco function from version 0.0.7 of the package: 
  Abbreviation line not found! Wrong file type?
  Abvr.line:                                                             
  Data line: Coefficients presented here differ from those used in DSSAT 
  Program will have to stop
  Check WORK.OUT for details. Routine was STANDC.

It works well when the eco file is written using the write_eco function from version 0.0.6 (and earlier) of the package.

See here-attached the different versions of the eco files (added extension .txt to be able to attach them ...). 

[WHCER048_006.ECO.txt](https://github.com/palderman/DSSAT/files/11331655/WHCER048_006.ECO.txt)
[WHCER048_007.ECO.txt](https://github.com/palderman/DSSAT/files/11331656/WHCER048_007.ECO.txt)

all the best,
Samuel

**Comment by palderman** [comment]
Hi @sbuis,

Thanks for pointing this out. I see what the problem is. The comments are not being prefixed with the "!' to indicate that it is a comment. I will try to get a bugfix out as soon as possible.

In the meantime, you can simply drop the comments before writing it to a file with:

```
attr(eco, "comments") <- NULL
write_eco(eco, "WHCER048.ECO")
```

**Comment by sbuis** [comment]
OK, great, thanks a lot for the quick answer.

**Comment by palderman** [comment]
Hi @sbuis,

I believe I have fixed the problem. It works for my checks, but would you be able to confirm that the current development version works for your situation?

In case you don't know, you can install the develop branch with:

```
devtools::install_github("palderman/DSSAT", ref = "develop")
```

Then you can reinstall the current release with:

```
install.packages("DSSAT")
```

**Comment by sbuis** [comment]
Hi Phillip,

yes, it's working with the develop branch without dropping the comments before writing the eco file.

FYI, I am using your DSSAT package for developping a model wrapper, in collab. with the DSSAT dev. team, for the [CroptimizR](https://sticsrpacks.github.io/CroptimizR/) and [CroPlotR](https://sticsrpacks.github.io/CroPlotR/) packages, to apply parameter estimation and evaluation methods to DSSAT.

all the best,
Samuel
