### ISSUE TITLE
Simulations Terminated while using run_dssat()

### ISSUE THREAD

**Issue by Peter-Kariuki** [palderman/DSSAT#46]
Dear P.Alderman
I am running this script but keep getting error on lines that do not exist in the experiment file. For example, the RORO7401.WHX has 83 lines but I get the following in warning.out file "File: Wheat/RORO7401.WHX   Line:   499   Error key: CSM". The simulation is hence terminated and no outputs.  The code snippet is pasted below

setwd("C:/DSSAT48/Wheat")
options(DSSAT.CSM = 'C:/DSSAT48/DSCSM048.EXE')

library(DSSAT)
#> When using the 'DSSAT' package for publications please cite all of the
#> following:
#> 
#>   Alderman, P.D. 2023. DSSAT: A Comprehensive R Interface for the DSSAT
#>   Cropping Systems Model. R package version 0.0.7. DOI:
#>   10.5281/zenodo.4091381. https://CRAN.R-project.org/package=DSSAT.
#> 
#>   Alderman, P.D. 2020. "A Comprehensive R Interface for the DSSAT
#>   Cropping Systems Model." Computers and Electronics in Agriculture
#>   172: 105325. DOI: 10.1016/j.compag.2020.105325.
#> 
#>   Jones, J.W., G. Hoogenboom, C.H. Porter, K.J. Boote, W.D. Batchelor,
#>   L.A. Hunt, P.W. Wilkens, U. Singh, A.J. Gijsman, and J.T. Ritchie.
#>   2003. "The DSSAT Cropping System Model." European Journal of Agronomy
#>   18 (3-4): 235-265.
#> 
#>   Hoogenboom, G., C.H. Porter, K.J. Boote, V. Shelia, P.W. Wilkens, U.
#>   Singh, J.W. White, S. Asseng, J.I. Lizaso, L.P. Moreno, W. Pavan, R.
#>   Ogoshi, L.A. Hunt, G.Y. Tsuji, and J.W. Jones. 2019. "The DSSAT Crop
#>   Modeling Ecosystem." In: Advances in Crop Modeling for a Sustainable
#>   Agriculture, edited by Kenneth J Boote, 173–216. Cambridge, United
#>   Kingdom: Burleigh Dodds Science Publishing.
#> 
#>   Hoogenboom, G., C.H. Porter, V. Shelia, K.J. Boote, U. Singh, J.W.
#>   White, W. Pavan, F.A.A. Oliveira, L.P. Moreno-Cadena, J.I. Lizaso, S.
#>   Asseng, D.N.L. Pequeno, B.A. Kimball, P.D. Alderman, K.R. Thorp, M.R.
#>   Jones, S.V. Cuadra, M.S. Vianna, F.J. Villalobos, T.B. Ferreira, J.
#>   Koo, L.A. Hunt, and J.W. Jones. <YEAR>. Decision Support System for
#>   Agrotechnology Transfer (DSSAT) Version <VERSION>. Gainesville,
#>   Florida, USA: DSSAT Foundation. https://DSSAT.net.
#> For BibTeX entries use toBibtex(citation("DSSAT"))
#> 
#> An existing value for DSSAT.CSM was found in options():
#> 
#>   C:\ DSSAT48\ DSCSM048.EXE
#> 
#> If this is not the correct executable, please use
#> 
#>   options(DSSAT.CSM="C:\ path\ to\ executable")
#> 
#>  to set the proper location and file name for DSSAT-CSM.

batch_file_path <- paste0("C:/dssat48/wheat/DSSBatch.V48")
write_dssbatch(x="RORO7401.WHX",trtno = 1:6,file_name =batch_file_path )

run_dssat(run_mode ="B", file_name = 'Wheat/RORO7401.WHX')

read_output('Summary.OUT')
#> Warning in file(con, "r"): cannot open file 'Summary.OUT': No such file or
#> directory
#> Error in file(con, "r"): cannot open the connection

No model outputs are generated. I only get ERROR.OUT and WARNING.OUT which reads
 "
Batch file not found.  Please check file name or create file.                  
  
File: Wheat/RORO7401.WHX   Line:   499   Error key: CSM   
"
I would greatly appreciate your help on this.
Best regards
Peter.

**Comment by palderman** [comment]
Please try running:

```
run_dssat(run_mode = "B", file_name = batch_file_path)
```

Does the error persist?

**Comment by Peter-Kariuki** [comment]
Hi P.Alderman,
Thank you for your prompt response. Sorry for my delayed response I have been away. 
I have tried it out and now have the output. Thank you so much for your help!

**Comment by Peter-Kariuki** [comment]
Hi P. Alderman,
One more question, since the write_dssbatch() takes in the experiment filex, how do I make my simulation take into account the weather and soil files? Is there some documentation/tutorial one can follow through?
