### ISSUE TITLE
Problem reading XLAT in summary.out using read_output()

### ISSUE THREAD

**Issue by lpmorenoc** [palderman/DSSAT#47]
The XLAT in the summary.out is read with just the last 3 decimals but without considering the integer. E.g.,  9.364 is read as 0.364
![image](https://github.com/palderman/DSSAT/assets/6476135/34be8f45-b8c2-49b0-b4fb-6c85679863a8)

![image](https://github.com/palderman/DSSAT/assets/6476135/35858997-0df0-4f97-b044-a4671c403d93)

**Comment by palderman** [comment]
Hi @lpmorenoc, Sorry it has taken so long for me to get to this! I think I have it fixed in the `develop` branch. Would you be able to install from there and check to see if that resolves the issue?

```
devtools::install_github("palderman/DSSAT", ref = "develop")
```

or

```
remotes::install_github("palderman/DSSAT", ref = "develop")
```

**Comment by palderman** [comment]
I think this issue is resolved, but please let me know if I need to reopen it.

**Comment by lpmorenoc** [comment]
Hi @palderman yes the issue was solved :)
