### ISSUE TITLE
write_filex() function does not write simulation controls section with multiple levels in the appropriate format

### ISSUE THREAD

**Issue by gonzarizzo** [palderman/DSSAT#50]
Hi @palderman ,

I am having problems with the `write_filex()` function. I am preparing a MZX file to run multiple simulations at once. In these simulations I have to set different simulation's starting date (i.e., multiple levels in the SM - factor levels). The problem is that when I set multiple levels in the new filex, the `write_filex()` function write the lines as follows (see picture below):

![image](https://github.com/palderman/DSSAT/assets/97065192/ab0140d4-1479-4536-a09b-25037ec154bc)

However, DSSAT requires each level to be written in a separate section as follows (see picture below):

![image](https://github.com/palderman/DSSAT/assets/97065192/a388709d-073b-439a-b757-99f21b9f0f7a)

Please, find a reproductible example below (just pay attention to the update on the simulation controls and how this section is exported - which does not work on DSSAT):

```
library(tidyverse)
library(DSSAT)
options(DSSAT.CSM = "/DSSAT48/dscsm048")
file.copy("/DSSAT48/Maize/FLSC8101.MZX", ".")
fileX <- read_filex("FLSC8101.MZX")

fileX$`TREATMENTS                        -------------FACTOR LEVELS------------` <-
  fileX$`TREATMENTS                        -------------FACTOR LEVELS------------` %>%
  mutate(
    N = list(1:4),
    SM = list(c(1,1,2,2))
  )

fileX$`SIMULATION CONTROLS` <-
  fileX$`SIMULATION CONTROLS` %>%
  mutate(N = list(c(1, 2)),
         SDATE = list(c(as.POSIXct(c("1981-10-06", "1982-10-06")))))

# write the fileX
write_filex(fileX, "FLSC8102.MZX", force_std_fmt = FALSE)
```

Thank you very much,
Gonzalo

**Comment by palderman** [comment]
Hi @gonzarizzo,

Thanks for raising this issue. I think the problem stems from the use of list columns for `N` and `SDATE`. The following code works for me to achieve what I think you are trying to do. Let me know if I've misunderstood your goal.

```
library(tidyverse)
library(DSSAT)

options(DSSAT.CSM = "/DSSAT48/dscsm048")
file.copy("/DSSAT48/Maize/FLSC8101.MZX", ".")
fileX <- read_filex("FLSC8101.MZX")

fileX$`TREATMENTS                        -------------FACTOR LEVELS------------` <-
  fileX$`TREATMENTS                        -------------FACTOR LEVELS------------` |>
  slice(rep(1:2, each = 2)) |>
  mutate(
    N = 1:4,
    SM = rep(1:2, each = 2)
  )

fileX$`SIMULATION CONTROLS` <-
  fileX$`SIMULATION CONTROLS` |>
  slice(rep(1, 2)) |>
  mutate(N = 1:2,
         SDATE = as.POSIXct("1981-10-06", "1982-10-06"))

# write the fileX
write_filex(fileX, "FLSC8102.MZX", force_std_fmt = FALSE)
```

**Comment by gonzarizzo** [comment]
Hi @palderman! Amazing! That was exactly what I was looking for!

Thank you very much 🙏
Gonzalo
