### ISSUE TITLE
Error in Writing Experimental Files

### ISSUE THREAD

**Issue by smkuhlani** [palderman/DSSAT#51]
I am getting this error, below:

Error in `map()`:
ℹ In index: 5.
Caused by error in `all_of()`:
! Can't subset columns that don't exist.
✖ Column `NOTES` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.

When I am writing a DSSAT experimental file, using this line:

DSSAT::write_filex(file_x,paste0('EXTE', formatC(width = 4, as.integer((i-1)), flag = "0"),'.SBX'))

Personal comment: The column 'NOTES' doesn't exist anywhere in the script or data sets we are using.

**Comment by palderman** [comment]
Hi @smkuhlani,

Thanks for reporting this. In order for me to properly diagnose the issue, please follow the following template:

**Describe the bug**
A clear and concise description of what the bug is.

**Reproducible Example**
Steps to reproduce the behavior (See [How to write a reproducible example](https://adv-r.had.co.nz/Reproducibility.html) for more information):
1. Load this file '...'
2. Run this command '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows, Linux]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by smkuhlani** [comment]
Thanks Phil. To reproduce my error:

1. Load this fileOpen the zipped folder 'R'. Then open script  '0_dssat_input_runAgWiseSB.R'
2. Run line 1 and 3, of  '0_dssat_input_runAgWiseSB.R'. (this takes a bit to run)
run the lines:
i=1
ex.name='test'jobs=1path.to.extdata='/extdata'
Open '2_dssat_expfileCGLabs_AgWiseSB.R' 
run lines 8-19, then 23-38. 

3. see error
Error is seen when i run, line 38: 'DSSAT::write_filex(file_x,paste0('EXTE', formatC(width = 4, as.integer((i-1)), flag = "0"),'.SBX'))'

Error in `map()`:
ℹ In index: 5.
Caused by error in `all_of()`:
! Can't subset columns that don't exist.
✖ Column `NOTES` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.


Expected behaviour
Error should not appear all.
In /extdata, a folder named 'test' will appear. In the folder 'test', will be individual files with folders, labelled 'EXTE0000, EXTE0001, EXTE0002, EXTE0003. Each EXTEXXXXX, represents a coordinate. Each EXTEXXXX, will contain a NEW.SOL, SOIL.SOL, WHTEXXXX.WTH and EXTEXXXX.SBX

Run: 
Open script  '0_dssat_input_runAgWiseSB.R'
run lines 12-13

 Expected behaviour
 Normal DSSAT simulation output. The output file will be EXTEXXXX.OUT

    OS: [ Linux]
    Version [R version 4.3.1 ] 


Hope this helps.






https://cgiar-my.sharepoint.com/:f:/g/personal/s_mkuhlani_cgiar_org/Evb-S0sUdmZIgp4MX1Wz-oUBkiZY8h_Eacz0-tRZdUut_Q?e=2aN5aG

[extdata.zip](https://github.com/palderman/DSSAT/files/13260723/extdata.zip)

[R.zip](https://github.com/palderman/DSSAT/files/13260722/R.zip)

**Comment by maria-quade** [comment]
Dear Mr. Alderman,
I am now getting the same error (after installing your development branch because of the write_sol problem).
It seems that the write_filex() function now needs definitions of 

(EXAMPLE from KSAS8101.WHX a default x-file)
@ PAREA  PRNO  PLEN  PLDR  PLSP  PLAY HAREA  HRNO  HLEN  HARM.........
    -99   -99   -99   -99   -99   -99   -99   -99   -99   -99
@NOTES
Documented in Wagger,M.G. 1983 Nitrogen cycling in the plan-soil system.
Ph.D. thesis, Kansas State Univ..Mike Wagger currently thought to be at 
the Agronomy Dept,N.Carolina State Un

which is not nessesary mandatory to run an xfile.

When I try to write an x-file without adding this information, I get the same error message:

filex <- read_filex(filex_name)    #default file, do not change
write_filex(filex,filex_name)

Error in `map()`:
i In index: 4.
Caused by error in `all_of()`:
! Can't subset columns that don't exist.
x Columns `PAREA`, `PRNO`, `PLEN`, `PLDR`, `PLSP`, etc. don't exist.
Run `rlang::last_trace()` to see where the error occurred.

[JKDL1901.zip](https://github.com/palderman/DSSAT/files/13306708/JKDL1901.zip)

I have attached one of my x-files to reproduce the problem.

Thanks for looking into it!

Best, Maria

**Comment by palderman** [comment]
@smkuhlani  and @maria-quade,

Thank you both for your feedback. I will work on this today and see if I can at least get you a work-around by the end of the day.

**Comment by BB1464** [comment]
Dear @palderman I am also getting the same error, here is a reprex to reproduce the problem. 

``` r
# Load Required Packages

library(DSSAT)
#> When using the 'DSSAT' package for publications please cite all of the
#> following:
#> 
#>   Alderman, P.D. 2023. DSSAT: A Comprehensive R Interface for the DSSAT
#>   Cropping Systems Model. R package version 0.0.8. DOI:
#>   10.5281/zenodo.4091381. https://CRAN.R-project.org/package=DSSAT.
#> 
#>   Alderman, P.D. 2020. "A Comprehensive R Interface for the DSSAT
#>   Cropping Systems Model." Computers and Electronics in Agriculture
#>   172: 105325. DOI: 10.1016/j.compag.2020.105325.
#> 
#>   Jones, J.W., G. Hoogenboom, C.H. Porter, K.J. Boote, W.D. Batchelor,
#>   L.A. Hunt, P.W. Wilkens, U. Singh, A.J. Gijsman, and J.T. Ritchie.
#>   2003. "The DSSAT Cropping System Model." European Journal of Agronomy
#>   18 (3-4): 235-265.
#> 
#>   Hoogenboom, G., C.H. Porter, K.J. Boote, V. Shelia, P.W. Wilkens, U.
#>   Singh, J.W. White, S. Asseng, J.I. Lizaso, L.P. Moreno, W. Pavan, R.
#>   Ogoshi, L.A. Hunt, G.Y. Tsuji, and J.W. Jones. 2019. "The DSSAT Crop
#>   Modeling Ecosystem." In: Advances in Crop Modeling for a Sustainable
#>   Agriculture, edited by Kenneth J Boote, 173–216. Cambridge, United
#>   Kingdom: Burleigh Dodds Science Publishing.
#> 
#>   Hoogenboom, G., C.H. Porter, V. Shelia, K.J. Boote, U. Singh, J.W.
#>   White, W. Pavan, F.A.A. Oliveira, L.P. Moreno-Cadena, J.I. Lizaso, S.
#>   Asseng, D.N.L. Pequeno, B.A. Kimball, P.D. Alderman, K.R. Thorp, M.R.
#>   Jones, S.V. Cuadra, M.S. Vianna, F.J. Villalobos, T.B. Ferreira, J.
#>   Koo, L.A. Hunt, and J.W. Jones. <YEAR>. Decision Support System for
#>   Agrotechnology Transfer (DSSAT) Version <VERSION>. Gainesville,
#>   Florida, USA: DSSAT Foundation. https://DSSAT.net.
#> For BibTeX entries use toBibtex(citation("DSSAT"))
#> 
#> A DSSAT-CSM executable was found here:
#> 
#>   
#> 
#> If this is not the correct executable, please use
#> 
#>   options(DSSAT.CSM="C:\ \ path\ to\ executable")
#> 
#>  to set the proper location and file name for DSSAT-CSM.
library(tidyverse)

# Define the Location to the DSSAT Executable file

options(DSSAT.CSM = 'C:\\DSSAT48\\DSCSM048.EXE')

## Set the working directory to read in the potatoes files

setwd("C:/DSSAT48/Potato/")

# Read the Potatoes file_x file

x <- read_filex(file_name = 'AUCB7001.PTX')


# Write the Potatoes file_x file

write_filex(filex = x,file_name = 'AUCB7001.PTX')
#> Error in `map()`:
#> ℹ In index: 4.
#> Caused by error in `all_of()`:
#> ! Can't subset columns that don't exist.
#> ✖ Columns `PAREA`, `PRNO`, `PLEN`, `PLDR`, `PLSP`, etc. don't exist.
#> Backtrace:
#>      ▆
#>   1. ├─DSSAT::write_filex(filex = x, file_name = "AUCB7001.PTX")
#>   2. │ ├─base::unlist(...)
#>   3. │ └─base::lapply(...)
#>   4. │   └─DSSAT (local) FUN(X[[i]], ...)
#>   5. │     └─DSSAT::write_tier(...)
#>   6. │       └─... %>% unlist()
#>   7. ├─base::unlist(.)
#>   8. ├─purrr::map(...)
#>   9. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  10. │   ├─purrr:::with_indexed_errors(...)
#>  11. │   │ └─base::withCallingHandlers(...)
#>  12. │   ├─purrr:::call_with_cleanup(...)
#>  13. │   └─DSSAT (local) .f(.x[[i]], ...)
#>  14. │     └─tier_data %>% select(all_of(tier_names))
#>  15. ├─dplyr::select(., all_of(tier_names))
#>  16. ├─dplyr:::select.data.frame(., all_of(tier_names))
#>  17. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
#>  18. │   └─tidyselect:::eval_select_impl(...)
#>  19. │     ├─tidyselect:::with_subscript_errors(...)
#>  20. │     │ └─rlang::try_fetch(...)
#>  21. │     │   └─base::withCallingHandlers(...)
#>  22. │     └─tidyselect:::vars_select_eval(...)
#>  23. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#>  24. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
#>  25. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#>  26. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
#>  27. │               └─tidyselect:::eval_context(expr, context_mask, call = error_call)
#>  28. │                 ├─tidyselect:::with_chained_errors(...)
#>  29. │                 │ └─rlang::try_fetch(...)
#>  30. │                 │   ├─base::tryCatch(...)
#>  31. │                 │   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  32. │                 │   │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  33. │                 │   │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  34. │                 │   └─base::withCallingHandlers(...)
#>  35. │                 └─rlang::eval_tidy(as_quosure(expr, env), context_mask)
#>  36. ├─tidyselect::all_of(tier_names)
#>  37. │ └─tidyselect:::as_indices_impl(x, vars = vars, strict = TRUE)
#>  38. │   └─tidyselect:::chr_as_locations(x, vars, call = call, arg = arg)
#>  39. │     └─vctrs::vec_as_location(...)
#>  40. └─vctrs (local) `<fn>`()
#>  41.   └─vctrs:::stop_subscript_oob(...)
#>  42.     └─vctrs:::stop_subscript(...)
#>  43.       └─rlang::abort(...)
```

<sup>Created on 2023-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16 ucrt)
#>  os       Windows 10 x64 (build 19045)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       Africa/Lagos
#>  date     2023-11-11
#>  pandoc   3.1.8 @ C:/PROGRA~1/Pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  bit           4.0.5   2022-11-15 [2] CRAN (R 4.3.0)
#>  bit64         4.0.5   2020-08-30 [2] CRAN (R 4.3.0)
#>  cli           3.6.1   2023-03-23 [1] CRAN (R 4.3.1)
#>  colorspace    2.1-0   2023-01-23 [1] CRAN (R 4.3.1)
#>  crayon        1.5.2   2022-09-29 [1] CRAN (R 4.3.1)
#>  digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.1)
#>  dplyr       * 1.1.3   2023-09-03 [1] CRAN (R 4.3.1)
#>  DSSAT       * 0.0.8   2023-11-11 [1] Github (palderman/DSSAT@81a583f)
#>  evaluate      0.21    2023-05-05 [1] CRAN (R 4.3.1)
#>  fansi         1.0.4   2023-01-22 [1] CRAN (R 4.3.1)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.1)
#>  forcats     * 1.0.0   2023-01-29 [2] CRAN (R 4.3.0)
#>  fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.1)
#>  generics      0.1.3   2022-07-05 [1] CRAN (R 4.3.1)
#>  ggplot2     * 3.4.3   2023-08-14 [1] CRAN (R 4.3.1)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.1)
#>  gtable        0.3.3   2023-03-21 [2] CRAN (R 4.3.0)
#>  hms           1.1.3   2023-03-21 [1] CRAN (R 4.3.1)
#>  htmltools     0.5.6   2023-08-10 [1] CRAN (R 4.3.1)
#>  knitr         1.43    2023-05-25 [1] CRAN (R 4.3.1)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.3.1)
#>  lubridate   * 1.9.2   2023-02-10 [2] CRAN (R 4.3.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.1)
#>  munsell       0.5.0   2018-06-12 [2] CRAN (R 4.3.0)
#>  pillar        1.9.0   2023-03-22 [1] CRAN (R 4.3.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.3.1)
#>  purrr       * 1.0.2   2023-08-10 [1] CRAN (R 4.3.1)
#>  R.cache       0.16.0  2022-07-21 [2] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2   2022-06-13 [2] CRAN (R 4.3.0)
#>  R.oo          1.25.0  2022-06-12 [2] CRAN (R 4.3.0)
#>  R.utils       2.12.2  2022-11-11 [2] CRAN (R 4.3.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.3.1)
#>  readr       * 2.1.4   2023-02-10 [2] CRAN (R 4.3.0)
#>  reprex        2.0.2   2022-08-17 [2] CRAN (R 4.3.0)
#>  rlang         1.1.1   2023-04-28 [1] CRAN (R 4.3.1)
#>  rmarkdown     2.24    2023-08-14 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.1)
#>  scales        1.2.1   2022-08-20 [2] CRAN (R 4.3.0)
#>  sessioninfo   1.2.2   2021-12-06 [2] CRAN (R 4.3.0)
#>  stringi       1.7.12  2023-01-11 [1] CRAN (R 4.3.0)
#>  stringr     * 1.5.0   2022-12-02 [1] CRAN (R 4.3.1)
#>  styler        1.10.0  2023-05-24 [2] CRAN (R 4.3.0)
#>  tibble      * 3.2.1   2023-03-20 [1] CRAN (R 4.3.1)
#>  tidyr       * 1.3.0   2023-01-24 [2] CRAN (R 4.3.0)
#>  tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.3.1)
#>  tidyverse   * 2.0.0   2023-02-22 [2] CRAN (R 4.3.0)
#>  timechange    0.2.0   2023-01-11 [2] CRAN (R 4.3.0)
#>  tzdb          0.4.0   2023-05-12 [2] CRAN (R 4.3.0)
#>  utf8          1.2.3   2023-01-31 [1] CRAN (R 4.3.1)
#>  vctrs         0.6.3   2023-06-14 [1] CRAN (R 4.3.1)
#>  vroom         1.6.3   2023-04-28 [2] CRAN (R 4.3.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.3.1)
#>  xfun          0.40    2023-08-09 [1] CRAN (R 4.3.1)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.3.0)
#> 
#>  [1] C:/Users/USER/AppData/Local/R/win-library/4.3
#>  [2] C:/Program Files/R/R-4.3.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by BB1464** [comment]
@palderman @maria-quade @smkuhlani, I was able to fix this by uninstalling and then reinstalling my DSSAT version again; then I was able to write the filex from R.

**Comment by palderman** [comment]
@BB1464, did you install from github or CRAN?

**Comment by BB1464** [comment]
@palderman I install the DSSAT software again on my Machine version 4.8, I discovered that in version 4.8.2 there are some columns that are missing there that is why @maria-quade was getting that error message; the DSSAT package I am using is the stable version. I suggest they should revert back to DSSAT version 4.8 until we find a way in fixing the issues of missing column names!!!

**Comment by palderman** [comment]
I'm on track with a solution, but need to complete some testing to make sure it works as intended.

**Comment by BB1464** [comment]
Thanks @palderman I will be looking forward to it!!!

**Comment by palderman** [comment]
Hi @BB1464 , @smkuhlani , and @maria-quade ,

Sorry for the long delay. I have code up on the `develop` branch that solves this for my current testing environment. Would you mind installing the `develop` branch from the repo:

```
remotes::install_github("palderman/DSSAT", ref = "develop")
```

and confirming that it works for you, too?

**Comment by BB1464** [comment]
@palderman thank you very much for this, the code is now working. You can mark this issue as closed.!!!
