### ISSUE TITLE
`read_sol()` function is not reading well a soil profile created by `write_sol()`

### ISSUE THREAD

**Issue by lpmorenoc** [palderman/DSSAT#52]
**Describe the bug**
`read_sol()` function is not reading well a soil profile created by `write_sol()`. Initially, I thought it was because the profile name I defined was shorter than the default profile name of DSSAT. However, after adding white spaces I was able to read the profile but it is read as two soil profiles instead of 1. I am using your develop branch `remotes::install_github("palderman/DSSAT", ref = "develop")`

**Reproducible Example**

**1.** Load the develop branch of the package.

```
devtools::install_github("palderman/DSSAT", ref = "develop")
require('DSSAT')

```
**2.** Read the soil file created previously by `read_sol()` [SOIL.zip](https://github.com/palderman/DSSAT/files/13877011/SOIL.zip)
```
setwd("D:/OneDrive - CGIAR/agwise/DSSAT/soil issue ")
test <- DSSAT::read_sol("SOIL.SOL", id_soil = "TRAN00001 ")
```

**3.**  See the error: We obtain two soil profiles instead of one but each of them is incomplete:

```
> test
       PEDON   SOURCE TEXTURE DEPTH DESCRIPTION   SITE COUNTRY    LAT   LONG   SCS FAMILY SCOM
1  TRAN00001 ISRIC V2     SIC    17  silty clay   <NA>    <NA>     NA     NA         <NA> <NA>
2 TRAN00001      <NA>    <NA>    NA        <NA> Eldama   Kenya -0.025 35.625 Unclassified   BN
  SALB SLU1 SLDR SLRO SLNF SLPF  SMHB  SMPX  SMKE                     SLB
1   NA   NA   NA   NA   NA   NA  <NA>  <NA>  <NA>                      NA
2 0.12  4.5  0.2   73    1 0.92 IB001 IB001 IB001 5, 15, 30, 60, 100, 200
                    SLMH                                     SLLL
1                     NA                                       NA
2 NA, NA, NA, NA, NA, NA 0.283, 0.256, 0.273, 0.295, 0.321, 0.323
                                      SDUL                                     SSAT
1                                       NA                                       NA
2 0.407, 0.392, 0.401, 0.414, 0.443, 0.449 0.570, 0.537, 0.527, 0.512, 0.507, 0.506
                                      SRGF                         SSKS
1                                       NA                           NA
2 1.000, 1.000, 0.638, 0.407, 0.202, 0.050 1.0, 0.7, 0.5, 0.2, 0.1, 0.0
                                SBDM                               SLOC
1                                 NA                                 NA
2 1.20, 1.20, 1.20, 1.20, 1.23, 1.27 5.72, 3.40, 3.19, 2.50, 0.60, 0.03
                                SLCL                               SLSI                   SLCF
1                                 NA                                 NA                     NA
2 43.8, 40.0, 44.0, 49.0, 54.4, 54.8 31.0, 31.0, 29.0, 26.0, 23.5, 22.7 NA, NA, NA, NA, NA, NA
                                SLNI                               SLHW                   SLHB
1                                 NA                                 NA                     NA
2 0.40, 0.33, 0.29, 0.21, 0.20, 0.16 5.40, 5.40, 5.30, 5.30, 5.50, 5.53 NA, NA, NA, NA, NA, NA
                                SCEC                   SADC
1                                 NA                     NA
2 29.3, 26.2, 25.0, 25.1, 24.5, 24.4 NA, NA, NA, NA, NA, NA
```

**Expected behavior**
I was expecting to have just one soil profile based on the soil file that I am reading (with just one soil profile).

**Desktop:**
 - OS: Windows
 - Version: 11 Pro

@palderman is it possible that every time you correct a bug in the DSSAT package, you update the version number even if we are installing it from your develop branch? the main reason is that @smkuhlani @egbendito and @meklitC are running a code using your package and we need to be sure that each of us is using the same version.

**Comment by palderman** [comment]
It seems that the 9-digit `PEDON` code is the source of the problem. Let me see if I can figure out a work around.

By the way, thanks for the suggestion about updating the version number. I will try to do that in the future. Maybe that will help me to keep the NEWS.md up to date, too.

**Comment by palderman** [comment]
The solution was fairly simple. It now removes all spaces before merging the first line of the profile with the rest. It now works with the example file you attached above and does not require you to specify the soil id with the extra space.

Please install the current `develop` branch and confirm that it works for you, e.g. (using your prior example):

```
devtools::install_github("palderman/DSSAT", ref = "develop")
library(DSSAT)

setwd("D:/OneDrive - CGIAR/agwise/DSSAT/soil issue ")

test <- DSSAT::read_sol("SOIL.SOL", id_soil = "TRAN00001")
```

**Comment by lpmorenoc** [comment]
HI @palderman it is working now! thanks for the quick help 🥇
