### ISSUE TITLE
write_sol() trims PEDON to 9 characters instead of 10 (i.e., "99SD00000" instead of "99SD000001")

### ISSUE THREAD

**Issue by valentinapereyra** [palderman/DSSAT#54]
**Describe the bug**

I'm appending several soil profiles created as Tibbles to a .SOL file, but the PEDON (id) is getting trimmed to 9 characters after the asterisk (*). There's a warning saying, "Warning: Column PEDON values were trimmed to fit specified column width."

1. Load this file
soil <- tibble(PEDON = "99SD000001",
                   SOURCE = "SSURGO",
                   TEXTURE = "S",
                   DEPTH = 200,
                   DESCRIPTION = "Barnes:418720",
                   SITE = "SD",
                   COUNTRY = "USA",
                   LAT = 44.36,
                   LONG = -96.84,
                   `SCS FAMILY` = NA %>% as.character(),
                   SCOM = NA,
                   SALB = 0.13,
                   SLU1 = 10,
                   SLDR = 0.5,
                   SLRO =	77,
                   SLNF = 1,
                   SLPF = 1,
                   SMHB = "IB001",
                   SMPX = "SA001",
                   SMKE = "IB001",
                   SLB = list(c(20, 40, 60, 80, 100, 120, 140, 160, 180, 200)),
                   SLMH = NA,
                   SLLL = list(c(0.12700000, 0.12700000, 0.12700000, 0.18076312, 0.18059782,
                                 0.18059782, 0.18059782, 0.18053170, 0.18053170, 0.18053170)),
                   SDUL = list(c(0.23500000, 0.23500000, 0.23500000, 0.31433341, 0.31424432,
                                 0.31424432, 0.31424432, 0.31420868, 0.31420868, 0.31420868)),
                   SSAT = list(c(0.39100000, 0.39100000, 0.39100000, 0.41808465, 0.41783645,
                                 0.41783645, 0.41783645, 0.41773718, 0.41773718, 0.41773718)),
                   SRGF = list(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1)),
                   SSKS = list(c(244, 244, 244, 244, 244, 244, 244, 244, 244, 244)),
                   SBDM = list(c(1.6140000, 1.6140000, 1.6140000, 1.5394257, 1.5400834,
                                 1.5400834, 1.5400834, 1.5403465, 1.5403465, 1.5403465)),
                   SLOC = list(c(1.34000000, 1.34000000, 1.34000000, 1.16279070, 0.43604651,
                                 0.43604651, 0.43604651, 0.14534884, 0.14534884, 0.14534884)),
                   SLCL = list(c(21, 21, 21, 30, 30, 30, 30, 30, 30, 30)),
                   SLSI = list(c(29, 29, 29, 36, 36, 36, 36, 36, 36, 36)),
                   SLCF = list(c(51, 51, 51, 34, 34, 34, 34, 34, 34, 34)),
                   SLNI = list(NA) %>% as.double(),
                   SLHW = list(NA) %>% as.double(),
                   SLHB = list(NA) %>% as.double(),
                   SCEC = list(NA) %>% as.double(),
                   SADC = list(NA) %>% as.double())

write_sol(soil, '../../DSSAT/sol/SOIL2.SOL') # save on your own folder

See this warning and exported result:

Warning: Column PEDON values were trimmed to fit specified column width. Please check output for introduced errors.

*99SD00000  SSURGO      S       200 Barnes:418720
@SITE        COUNTRY          LAT     LONG SCS FAMILY
SD           USA           44.360  -96.840 -99
@ SCOM  SALB  SLU1  SLDR  SLRO  SLNF  SLPF  SMHB  SMPX  SMKE
   -99  0.13 10.00  0.50  77.0  1.00  1.00 IB001 SA001 IB001
@  SLB  SLMH  SLLL  SDUL  SSAT  SRGF  SSKS  SBDM  SLOC  SLCL  SLSI  SLCF  SLNI  SLHW  SLHB  SCEC  SADC
    20   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99
    40   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99
    60   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99
    80   -99 0.181 0.314 0.418 1.000  244.  1.54 1.163  30.0  36.0  34.0   -99   -99   -99   -99   -99
   100   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99
   120   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99
   140   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99
   160   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99
   180   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99
   200   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99

**Expected behavior**
As you can see the PEDON is "99SD00000" instead of "99SD000001". I've been dealing since last year with this issue.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 14.5 macOS Sonoma

**Comment by palderman** [comment]
Hi @valentinapereyra ,

I'm sorry you are having this issue. There was a bug in a previous version that I believe has now been fixed. Would you please confirm which version of the DSSAT package you are using? The version I tested was:

``` r
packageVersion("DSSAT")
#> [1] '0.0.9'
```

 I tried to duplicate the error with the current release version (v0.0.9) and I get no warning or error:

``` r
tibble::tibble(
    PEDON = "99SD000001",
    SOURCE = "SSURGO",
    TEXTURE = "S",
    DEPTH = 200,
    DESCRIPTION = "Barnes:418720",
    SITE = "SD",
    COUNTRY = "USA",
    LAT = 44.36,
    LONG = -96.84,
    `SCS FAMILY` = NA_character_,
    SCOM = NA_character_,
    SALB = 0.13,
    SLU1 = 10,
    SLDR = 0.5,
    SLRO = 77,
    SLNF = 1,
    SLPF = 1,
    SMHB = "IB001",
    SMPX = "SA001",
    SMKE = "IB001",
    SLB = list(c(20, 40, 60, 80, 100, 120, 140, 160, 180, 200)),
    SLMH = NA_character_,
    SLLL = list(c(0.12700000, 0.12700000, 0.12700000, 0.18076312, 0.18059782,
                  0.18059782, 0.18059782, 0.18053170, 0.18053170, 0.18053170)),
    SDUL = list(c(0.23500000, 0.23500000, 0.23500000, 0.31433341, 0.31424432,
                  0.31424432, 0.31424432, 0.31420868, 0.31420868, 0.31420868)),
    SSAT = list(c(0.39100000, 0.39100000, 0.39100000, 0.41808465, 0.41783645,
                  0.41783645, 0.41783645, 0.41773718, 0.41773718, 0.41773718)),
    SRGF = list(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1)),
    SSKS = list(c(244, 244, 244, 244, 244, 244, 244, 244, 244, 244)),
    SBDM = list(c(1.6140000, 1.6140000, 1.6140000, 1.5394257, 1.5400834,
                  1.5400834, 1.5400834, 1.5403465, 1.5403465, 1.5403465)),
    SLOC = list(c(1.34000000, 1.34000000, 1.34000000, 1.16279070, 0.43604651,
                  0.43604651, 0.43604651, 0.14534884, 0.14534884, 0.14534884)),
    SLCL = list(c(21, 21, 21, 30, 30, 30, 30, 30, 30, 30)),
    SLSI = list(c(29, 29, 29, 36, 36, 36, 36, 36, 36, 36)),
    SLCF = list(c(51, 51, 51, 34, 34, 34, 34, 34, 34, 34)),
    SLNI = list(NA_real_),
    SLHW = list(NA_real_),
    SLHB = list(NA_real_),
    SCEC = list(NA_real_),
    SADC = list(NA_real_)) |>
  DSSAT::write_sol("TEST.SOL", append = FALSE)

readLines("TEST.SOL")
#>  [1] "*SOILS: General DSSAT Soil Input File"                                                                 
#>  [2] ""                                                                                                      
#>  [3] "*99SD000001  SSURGO      S       200 Barnes:418720"                                                    
#>  [4] "@SITE        COUNTRY          LAT     LONG SCS FAMILY"                                                 
#>  [5] " SD          USA           44.360  -96.840 -99"                                                        
#>  [6] "@ SCOM  SALB  SLU1  SLDR  SLRO  SLNF  SLPF  SMHB  SMPX  SMKE"                                          
#>  [7] "   -99  0.13 10.00  0.50  77.0  1.00  1.00 IB001 SA001 IB001"                                          
#>  [8] "@  SLB  SLMH  SLLL  SDUL  SSAT  SRGF  SSKS  SBDM  SLOC  SLCL  SLSI  SLCF  SLNI  SLHW  SLHB  SCEC  SADC"
#>  [9] "    20   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99"
#> [10] "    40   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99"
#> [11] "    60   -99 0.127 0.235 0.391 1.000  244.  1.61 1.340  21.0  29.0  51.0   -99   -99   -99   -99   -99"
#> [12] "    80   -99 0.181 0.314 0.418 1.000  244.  1.54 1.163  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [13] "   100   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [14] "   120   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [15] "   140   -99 0.181 0.314 0.418 1.000  244.  1.54 0.436  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [16] "   160   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [17] "   180   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99"
#> [18] "   200   -99 0.181 0.314 0.418 1.000  244.  1.54 0.145  30.0  36.0  34.0   -99   -99   -99   -99   -99"
```

**Comment by valentinapereyra** [comment]
Hi Alderman. 

Thank you for your prompt answer!
I'm also using the version 0.0.9

I just checked with a friend with a Windows 11 pro (10.0.22631 Build 22631), and the code also worked correctly for him.
So I guess it is something related to the Mac. Honestly, I don't know what it could be and if it would be possible to fix it.

**Comment by palderman** [comment]
That's very unexpected. I am running on Linux (Ubuntu 20.04.6 LTS), which I would expect to perform very similarly to Mac. Perhaps you could try reinstalling?

```r
install.packages("DSSAT")
```

**Comment by palderman** [comment]
You might also need to restart your R session for the reinstallation to take effect...

**Comment by valentinapereyra** [comment]
Yes, that just worked for me! Thanks!! I had already tried reinstalling the package, but I hadn't restarted the session.

**Comment by palderman** [comment]
Great! I'll mark this as closed then.
