### ISSUE TITLE
wrong format with read_cul()

### ISSUE THREAD

**Issue by maria-quade** [palderman/DSSAT#55]
Dear Mr. Alderman,

Since today my read_cul() doesn't read the cultivar file correctly. By reading the working cultivar file   

[WHCER048.txt](https://github.com/user-attachments/files/16280373/WHCER048.txt)
@VAR#  VAR-NAME........  EXP#   ECO#   P1V   P1D    P5    G1    G2    G3 PHINT
IB0101 WW_DD                . DE0001     2    85   430    32    29     1    62

It doesn't read VAR# and VAR-NAME correctly. When I save the same file without changing anything, it looks like this
[WHCER048.txt](https://github.com/user-attachments/files/16280395/WHCER048.txt)
@VAR# .........VAR-NAME  EXP#ECO#      P1V   P1D    P5    G1    G2    G3 PHINT
IB010           1 WW_DD     .DE0001     12    75   316    47    47     1    67

so the last digit from VAR#  was moved to VAR-NAME
 
I am using the R version 4.3.0 (2023-04-21 ucrt) -- "Already Tomorrow"
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Windows.

On my Linux server read_cul works fine.

Thank you in advance 

Best, Maria Quade

**Comment by palderman** [comment]
Hi @maria-quade,

I'm not able to detect any difference in the two files you uploaded. I'm also not able to duplicate the issue on my Linux laptop either. It's hard to diagnose without the ability to reproduce the error.

I have tried to construct a reproducible example based on what you uploaded. Can you confirm that the following code does indeed produce the error you are reporting for your Windows machine? You should be able to just copy the code and then run `reprex::reprex()` and directly paste the results here.

``` r
c("$CULTIVARS:WHCER048.20200721   Last edit: 20210-05-06 GH",
  "",
  "@VAR#  VAR-NAME........  EXP#   ECO#   P1V   P1D    P5    G1    G2    G3 PHINT",
  "IB0101 WW_DD                . DE0001     2    85   430    32    29     1    62",
  "") |>
  write(file.path(tempdir(), "WHCER048.CUL"))

DSSAT::read_cul(file.path(tempdir(), "WHCER048.CUL")) |>
  DSSAT::write_cul(file.path(tempdir(), "TESTFILE.CUL"))

readLines(file.path(tempdir(), "TESTFILE.CUL"))
#> [1] "$CULTIVARS:WHCER048.20200721   Last edit: 20210-05-06 GH"                      
#> [2] ""                                                                              
#> [3] ""                                                                              
#> [4] "@VAR#  VAR-NAME........  EXP#   ECO#   P1V   P1D    P5    G1    G2    G3 PHINT"
#> [5] "IB0101 WW_DD                . DE0001     2    85   430    32    29     1    62"
```

<sup>Created on 2024-07-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by maria-quade** [comment]
Dear Mr. Alderman,

Thank you for your reply and the time and effort you have put into this. I am not sure what caused this error last week, but fortunately it is now gone. 

Next time this happens, I will wait a few days before opening an issue. I hope you didn't spend to much time on this.

Thanks a lot for your help and support!

Best, Maria Quade

**Comment by palderman** [comment]
Glad it's working for you! I'll close this issue.
